# Site settings
title: Paul Davis
email: pauladamdavis@gmail.com
description: Front-end developer
url: "https://pad.gs" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
paginate_path: "/page/:num/"
sass:
    style: compressed

gems: ['jekyll-paginate']
