# Site settings
title: Paul Davis
email: pauladamdavis@gmail.com
description: Front-end developer
url: "https://pad.gs" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
paginate_path: "/page:num/"

gems: ['jekyll-paginate']